### PR TITLE
Refactor Reports

### LINKED ISSUE #8: Combined reports
We would need a report that combines all reports together in one big export to be used in another software for further analysis. It would make sense to add possibility to include and exclude some reports if needed. 

We have an alpha version here:

https://github.com/richinfante/iphonebackuptools/commit/dc101b12959e75ce20fcdb832b6105f581aadf51

Should we do pull request for this version or you implement it yourself?

### PR DESCRIPTION
**Pull request by richinfante**
- [x] Make formatting reports more modular (backwards-compatible)
- [x] Reports can specify compatible iOS Versions, or supply multiple versions of the formatter for different iOS version ranges.
    - See `tools/reports/_example.js` for an example reporter module and how to specify supported iOS Versions
- [x] Remove old-style command flags
   - `-c`, `-m`, `--dump`
   - `-f` (for filtering), is replaced by `-f` for formatting reports.
- [x] Formatted JSON output
- [x] Promise based API for developing reports that return data asynchronously.
   - If an output file is specified, the returned output from the promise is written to a file.
   - Otherwise, it is simply printed to STDOUT.
- [x] Multiple reporting output
    - Output multiple tables to STDOUT
    - Unified JSON output
    - File output based on report names.

You can specify report types using the `--formatter <type>` or `-f <type>` flags. Currently, the following reporters are implemented / planned:
- `csv` csv output for viewing in excel
- `raw-csv` full-data csv output for viewing in excel
- `json` formatted json output
- `raw-json` full-data output
- `table` formatted table for easy viewing in the terminal

You can specify an output file/directory to write to disk using the `-o <path>` or `--output <path>` flags.

Additionally, for `json` and `raw-json`, the option to join the reports together is given using the flag `--join-reports`

Fixes #8 

## Breaking Changes
Removed: `-f` shortcut for filtering. using `--filter` is now required. The `-f` flag still exists but is for selecting an output formatter, since `--filter` is used rarely.
Removed `-c` shortcut for listing conversations in favor of using `-r conversations`
Removed `-m` shortcut for listing messages in favor of using `-r messages`
Removed `--dump` in favor of using  the new raw json formatter: `-f raw`

### CODE REVIEW

**Comment by timotoots** [comment]
Is "formatted json output" the same as "table", but in json format?

**Comment by timotoots** [comment]
When do you plan to merge it? It would make sense to create new reports with the new convention!

**Comment by richinfante** [comment]
I'll be merging this into master soon, I've just got a few small things to finish up.

**Comment by richinfante** [comment]
The formatted json output will be essentially a JSON representation of the table. There's also a new report called `raw` which is the same as the current json "dump" functionality accessed by using `--dump`

**Comment by timotoots** [comment]
Perfect!

**Pull request merged**
